FROM nvidia/cuda:11.8.0-devel-ubuntu22.04

ENV DEBIAN_FRONTEND=noninteractive
ENV FORCE_CUDA="1"
ENV CUDA_HOME="/usr/local/cuda"

# configure timezone, our app depends on it.
RUN /usr/bin/ln -sf /usr/share/zoneinfo/America/Toronto /etc/localtime

# install software
RUN apt update \
    && apt -y install python3-dev python3-pip ffmpeg unzip wget curl cmake screen git libturbojpeg \
    && apt clean

RUN pip3 install -U pip

RUN pip3 install --no-cache-dir torch==2.0.1+cu118 torchvision==0.15.2+cu118 --index-url https://download.pytorch.org/whl/cu118

WORKDIR /app
RUN wget https://github.com/isl-org/ZoeDepth/releases/download/v1.0/ZoeD_M12_NK.pt -nv -O ./ZoeD_M12_NK.pt

COPY third_party/ZoeDepth/requirements.txt ./third_party/ZoeDepth/requirements.txt
RUN pip3 install --no-cache-dir -r /app/third_party/ZoeDepth/requirements.txt

COPY depthapp/requirements.txt ./depthapp/requirements.txt
RUN pip3 install --no-cache-dir -r /app/depthapp/requirements.txt

COPY third_party/ZoeDepth ./third_party/ZoeDepth/
RUN pip3 install -e third_party/ZoeDepth
RUN mv /app/ZoeD_M12_NK.pt /app/third_party/ZoeDepth/

COPY depthapp ./depthapp/
